const DESCRIPTIONS = {
  1984: "El Toleman TG184 con motor Hart 415T turbo de 4 cilindros, hasta 800 CV en clasificación. Hart era un constructor privado pequeño frente a los gigantes Porsche y Honda. Senna, en su primera temporada de F1, estuvo a punto de ganar Mónaco bajo la lluvia superando a Prost cuando la carrera fue detenida con Senna ya más rápido. Muchos creen que si la carrera hubiera continuado dos vueltas más, Senna habría ganado. Johnny Cecotto fue su compañero.",
  1985: "El Lotus 97T con motor Renault EF4 V6 turbo, 750 CV. Senna ganó sus dos primeras victorias en F1: Portugal bajo la lluvia con una ventaja de más de un minuto, y Bélgica en Spa. La victoria en Portugal fue una exhibición de control sobrenatural con el coche al límite en cada curva mojada. Elio de Angelis fue su compañero. Senna ya mostraba ese talento especial bajo la lluvia que le definiría toda su carrera.",
  1986: "El Lotus 98T con motor Renault EF15 V6 turbo, 900 CV en carrera y hasta 1.300 CV en clasificación. Senna clasificó en pole 8 veces pero el coche era poco fiable. Ganó en Detroit y España. Johnny Dumfries fue compañero. Curiosidad: Senna clasificó el Lotus en Jerez con tal brutalidad que superó la pole anterior por más de 2 segundos, destrozando el crono con un motor que literalmente explotaba de potencia.",
  1987: "El Lotus 99T con motor Honda RA167E V6 turbo, 1.000 CV, el primero con suspensión activa en la F1. Senna ganó en Mónaco y Detroit. En Mónaco tuvo un accidente en el túnel durante los entrenamientos chocando contra el muro a alta velocidad, salió ileso y volvió a clasificar en pole. Satoru Nakajima fue compañero. Era el último año de Senna con Lotus antes de dar el salto a McLaren.",
  1992: "El McLaren MP4/7A con motor Honda RA122E V12, 740 CV. Fue la temporada del Williams FW14B de Mansell, inalcanzable. Senna ganó 3 carreras, incluida Mónaco por quinta vez consecutiva. En Brasil, su tierra, llegó segundo ante el delirio del público. Berger fue compañero. Curiosidad: Senna y Mansell protagonizaron en Mónaco un duelo mano a mano en las últimas vueltas que quedó para la historia, con Mansell incapaz de adelantar pese a tener un coche superior.",
  1993: "El McLaren MP4/8 con motor Ford HB V8, 740 CV, tras la retirada de Honda. Prost exigió a Williams no fichar a Senna. Con un coche inferior, Senna ganó 5 carreras incluyendo Brasil entre lágrimas. En Donington protagonizó la que muchos consideran la mejor primera vuelta de la historia de la F1, adelantando a cuatro coches bajo la lluvia. Michael Andretti y Häkkinen fueron compañeros.",
  1994: "El Williams FW16 con motor Renault V10, 780 CV. Senna firmó con Williams para luchar por su cuarto título. Las primeras carreras mostraron problemas de adaptación al coche. En San Marino, el 1 de mayo de 1994, Senna falleció en el accidente en la curva Tamburello de Imola a 311 km/h. Tenía 34 años. Dejó el mundo del motor huérfano del talento más especial que había visto jamás. Hill fue su compañero.",
};

export default DESCRIPTIONS;
